### PR TITLE
BiDirectional JIRA Integration (Don't Merge)

### PR DESCRIPTION
**Pull request by devGregA**
Conflicts Resolved. Testing I didn't screw anything up

### CODE REVIEW

**Comment by devGregA** [comment]
@aaronweaver @grendel513 @mtesauro ^

**Comment by devGregA** [comment]
@aaronweaver @grendel513 @mtesauro figured out the issues doing one more manual pass and then this will be ready for your reviews

**Comment by devGregA** [comment]
@mtesauro @grendel513 @aaronweaver http://s2.quickmeme.com/img/49/49bd7440ec7c07183a676bf3f0182ee20621c20e5c3442d4bb451c76fe3529e9.jpg

I have a JIRA instance and Dojo instance I can share the creds for when someone is able to review

**Comment by devGregA** [comment]
found a minor issue. fixing

**Comment by devGregA** [comment]
okay @aaronweaver @mtesauro @grendel513  ready for review again

**Comment by aaronweaver** [comment]
@devGregA Reviewed and merged.

**Pull request merged**
