### PR TITLE
Use django's timezone mechanisms

### PR DESCRIPTION
**Pull request by patriknordlen**
This PR addresses an issue that possibly arose when timezone settings were moved to a model instead of settings.py, which is that this timezone setting wasn't honored.

The PR adds a middleware that will activate the proper timezone and changes lots and lots of datetime functions to instead use corresponding Django timezone aware functions using django.utils.timezone.

### CODE REVIEW

**Comment by patriknordlen** [comment]
Caught a bug...issuing fix shortly.

**Comment by devGregA** [comment]
@patriknordlen is this ready for testing / merging?

**Comment by patriknordlen** [comment]
@devGregA it is!

**Comment by devGregA** [comment]
@patriknordlen sanity checking now

**Pull request merged**
