### PR TITLE
API Importer Fix

### PR DESCRIPTION
**Pull request by aaronweaver**
When submitting a pull request, please make sure you have completed the following checklist:

- [ ] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
- [ ] If this is a new feature and not a bug fix, you've included the proper docuemntation under the /docs folder

### CODE REVIEW

**Comment by dkade** [comment]
@aaronweaver @devGregA it seems that those merges are missing Database migrations. 
For example: 
OperationalError: (1054, "Unknown column 'dojo_finding.line_number' in 'field list'") or 
OperationalError: (1054, "Unknown column 'dojo_finding.sourcefilepath' in 'field list'")

**Comment by aaronweaver** [comment]
@dkade Just to verify you did a makemigrations & migrate?

**Comment by devGregA** [comment]
https://defectdojo.readthedocs.io/en/latest/upgrading.html per @aaronweaver's comment

**Comment by dkade** [comment]
Yes I did, the fields were not created... But i just checked the 0001_initial.py and the fields are there, will try to understand why they are not being created. 

Sorry for the confusion, and thank you for the help.

**Comment by devGregA** [comment]
Weird, no need to apologize. Trying `python manage.py syncdb` might help if it still exists. That command might have been removed in django 1.11

**Pull request merged**
