### PR TITLE
Some PEP8 linting

### PR DESCRIPTION
**Pull request by cneill**
Did some basic PEP8 linting across various files. I didn't bother with the 80 character limit since most of the lines in question would require significant re-writes. I tried not to make any changes that would affect the actual code, but there are a couple minor modifications like using .format() in a few places.

### CODE REVIEW

**Comment by cneill** [comment]
Looking at failed build checks above, I don't think this patch has anything to do with the failure..

**Comment by devGregA** [comment]
Nice! Great stuff @cneill. @aaronweaver I think this is because Travis only supplies proper env variables for commits which is a pain. Trying to figure out how to fix this.

**Comment by devGregA** [comment]
found a fix. just a sec

**Comment by devGregA** [comment]
@aaronweaver  https://docs.travis-ci.com/user/pull-requests I don't think at this time we have to worry about any of our envs being leaked?

**Comment by devGregA** [comment]
I can add    - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./travis/run_on_pull_requests; fi'
to enable for PRs

**Comment by aaronweaver** [comment]
@devGregA The only one that should be protected is the API key for SRC:CLR.

**Comment by devGregA** [comment]
@cneill looks like you took out an import os that was required in settings.py.

**Comment by cneill** [comment]
My bad - didn't look like it was referenced in the file.

**Comment by devGregA** [comment]
going to roll back because I'm seeing other strange filter issues.

**Comment by devGregA** [comment]
Hey @cneill  there was another issue that I just patched if you can resubmit.

**Pull request merged**
