### PR TITLE
Modularize travis execution as jobs for parallel processing. 

### PR DESCRIPTION
**Pull request by secfigo**
This PR divides travis script into following jobs
1. integration-test
2. sourceclear
3. bandit
4. docker-bench-security
5. ansible (this is empty at the moment)

The tests are moved to into scripts/travis-integration-test.sh file. Bandit job is allowed to fail at the moment as there is lot of code which is not pep8 compliant. 

sourceclear job passes when `SRCCLR_API_TOKEN` is added to settings as env variable.

When submitting a pull request, please make sure you have completed the following checklist:

- [x] Your code is pep8 compliant (Dojo's code isn't currently pep8 compliant, but we're trying to correct that)
- [x] If this is a new feature and not a bug fix, you've included the proper docuemntation under the /docs folder

### CODE REVIEW

**Comment by secfigo** [comment]
@devGregA @aaronweaver for your review please. This is to modularize and also add production testing molecule (prod-install)

**Comment by aaronweaver** [comment]
@secfigo Looks like the failure is simply b/c env variables aren't available to a merge request. Question, the time has more than doubled from 7 minutes to 18 minutes. Can you comment on the time increase for the build?

**Comment by secfigo** [comment]
@aaronweaver the job finishes by 5 mins. Since the docker hub username is not present, it waits for someone to enter username. 

You can try running that job and see the time when its done with status checks

**Comment by secfigo** [comment]
@aaronweaver there you go, added some error checks, build is 5 mins and 11 seconds now.

**Comment by aaronweaver** [comment]
@secfigo Would you mind adding sourceclear to allowed failures? That way, we won't always have fails for PR's.

**Comment by devGregA** [comment]
@aaronweaver spoke to @mtesauro he has reviewed and is good with merging

**Comment by aaronweaver** [comment]
@devGregA Ok, once srcclr is set to not fail for PR merges.

**Pull request merged**
