### PR TITLE
Async Deduplication

### PR DESCRIPTION
**Pull request by devGregA**

### CODE REVIEW

**Comment by devGregA** [comment]
@aaronweaver  looks like there maybe an issue with the zap container?

**Comment by aaronweaver** [comment]
Hi @devGregA, The dojo container stopped so the link to zap failed. It's failing when it tried to load the user fixture. ImportError: cannot import name Dojo_User, from sample_data/initial_dojo_data.json.

Did the database structure change at all? We could re-export the data load. Something I've been thinking about is loading through the API vs. loading via fixtures.

  File "/django-DefectDojo/dojo/models.py", line 22, in <module>
    from dojo.tasks import async_dedupe
  File "/django-DefectDojo/dojo/tasks.py", line 19, in <module>
    from dojo.reports.widgets import report_widget_factory
  File "/django-DefectDojo/dojo/reports/widgets.py", line 14, in <module>
    from dojo.filters import EndpointFilter, ReportAuthedFindingFilter
  File "/django-DefectDojo/dojo/filters.py", line 16, in <module>
    from dojo.models import Dojo_User, Product_Type, Finding, \
ImportError: cannot import name Dojo_User
Data imported from: sample_data/initial_dojo_data.json

**Comment by devGregA** [comment]
thanks @aaronweaver  I'm re-running the build to see what happens.

**Comment by devGregA** [comment]
@aaronweaver I don't believe anything has changed. Wouldn't the regular install? I haven't had issues with the regular install.

**Comment by aaronweaver** [comment]
@devGregA Could you try this script on your local install? 

python /django-DefectDojo/manage.py loaddata /django-DefectDojo/docker/sample_data/initial_dojo_data.json

**Comment by devGregA** [comment]
@aaronweaver  ah mine fails as well

 load contenttypes.ContentType(pk=11): (1062, "Duplicate entry 'dojo-contact' for key 'django_content_type_app_label_45f3b1d93ec8c61c_uniq'")

**Comment by devGregA** [comment]
@aaronweaver  should I wipe my db before trying?

**Comment by aaronweaver** [comment]
Yes

**Comment by devGregA** [comment]
Hey Aaron I still get the same error after wiping the database

django.db.utils.IntegrityError: Problem installing fixture '/home/greg/again_dojo/django-DefectDojo/docker/sample_data/initial_dojo_data.json': Could not load contenttypes.ContentType(pk=11): (1062, "Duplicate entry 'dojo-contact' for key 'django_content_type_app_label_45f3b1d93ec8c61c_uniq'")

**Comment by grendel513** [comment]
@devGregA - is this one ready to go?

**Pull request merged**
