### PR TITLE
Fixing some date formatting issues

### PR DESCRIPTION
**Pull request by CCoffie**
Some of my date formatting for the import scan and re-import scan API endpoints were inconsistent and causing problems. So these changes should fix the problems.

### CODE REVIEW

**Comment by devGregA** [comment]
Thank you @CCoffie! I'm good with merging. Can someone second this please?

**Comment by aaronweaver** [comment]
@CCoffie I believe the convention of the date API should be: %Y-%m-%d not '/'

**Comment by grendel513** [comment]
+1 to @aaronweaver's comment

**Comment by devGregA** [comment]
hi @CCoffie please see comments above.

**Comment by devGregA** [comment]
closing. Haven't been able to get in touch with @CCoffie

**Pull request closed without merging**
