### PR TITLE
Bug fix deduplication: typo and self reference.

### PR DESCRIPTION
**Pull request by bartosznaumowicz-olx**
Greetings from OLX.
Bug fix deduplication: typo and self reference.

### CODE REVIEW

**Comment by devGregA** [comment]
hi @bartosznaumowicz-olx, thank you for your PR! I agree that we should not be using self since it isn't an instance method, however we would need to change the references to the calls. I think for now we should probably keep the self passing as is and just correct the typo.

**Comment by bartosznaumowicz-olx** [comment]
Self parameter creates an error:  
`[2017-05-31 08:49:46,927: ERROR/MainProcess] Task async_dedupe[d614d49f-6cbc-4d13-b7a9-c5a611777738] raised unexpected: TypeError('async_dedupe() takes at least 2 arguments (1 given)',)
dojo_1        | Traceback (most recent call last):
dojo_1        |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
dojo_1        |     R = retval = fun(*args, **kwargs)
dojo_1        |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
dojo_1        |     return self.run(*args, **kwargs)
dojo_1        | TypeError: async_dedupe() takes at least 2 arguments (1 given)
dojo_1        | [2017-05-31 08:49:46,929: ERROR/MainProcess] Pool callback raised exception: ValueError('too many values to unpack',)
dojo_1        | Traceback (most recent call last):
dojo_1        |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/billiard/pool.py", line 1700, in safe_apply_callback
dojo_1        |     fun(*args, **kwargs)
dojo_1        |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/worker/job.py", line 384, in on_success
dojo_1        |     return self.on_failure(ret_value)
dojo_1        |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/worker/job.py", line 443, in on_failure
dojo_1        |     self._log_error(exc_info, send_failed_event=send_failed_event)
dojo_1        |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/worker/job.py", line 514, in _log_error
dojo_1        |     task.send_error_email(context, einfo.exception)
dojo_1        |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/app/task.py", line 900, in send_error_email
dojo_1        |     self.ErrorMail(self, **kwargs).send(context, exc)
dojo_1        |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/utils/mail.py", line 190, in send
dojo_1        |     fail_silently=fail_silently)
dojo_1        |   File "/django-DefectDojo/venv/local/lib/python2.7/site-packages/celery/app/base.py", line 416, in mail_admins
dojo_1        |     to = [admin_email for _, admin_email in self.conf.ADMINS]
dojo_1        | ValueError: too many values to unpack`


`TypeError('async_dedupe() takes at least 2 arguments (1 given)',)`

**Comment by joaquinrinaudo-olx** [comment]
@devGregA @aaronweaver The reference to the calls are not using self. We've tested this and it's working  now.

**Comment by devGregA** [comment]
@joaquinrinaudo-olx will test soon. Finishing up a qualys importer.

**Comment by devGregA** [comment]
@joaquinrinaudo-olx, I tested this PR. It breaks the reports functionality. Please ensure new work is compatible with all aspects of DD.

**Comment by bartosznaumowicz-olx** [comment]
That's strange. Before this change reports func. was not working for us. After this change (self ref. removal and typo) it started to working fine...

I will investigate this.

**Comment by devGregA** [comment]
Maybe you changed the files but didn't commit them?

-- Greg Anderson
OWASP DefectDojo Project Leader
https://www.owasp.org/index.php/OWASP_DefectDojo_Project

**Pull request closed without merging**
