### PR TITLE
Update parser.py

### PR DESCRIPTION
**Pull request by jordanpotti**
Added support for DefectDojo to recognize mitigation status from Veracode XML imports.
Issue# 290

### CODE REVIEW

**Comment by devGregA** [comment]
Hi @jordanpotti thank you for your work on this! Would it not be better to mark a mitigated finding as `active=False` rather than `false_p=1`

**Comment by jordanpotti** [comment]
I'm not sure. In my eyes, if I have it marked as mitigated in the Veracode platform, the finding is basically a false positive when consolidating with other findings in DefectDojo. However, that might not be the best option for most users, I can change that to leave `false_p=1` out and since `active=False` is default, it shouldn't require any other changes.

**Comment by devGregA** [comment]
@grendel513 @aaronweaver @mtesauro can I get a second review please?

**Comment by devGregA** [comment]
Hi @jordanpotti  really appreciate you working on this. If you don't mind sending me an address and a shirt size to greg.anderson@owasp.org. We'll send you some dojo swag.

**Pull request merged**
