### PR TITLE
Fix for #360 and #358

### LINKED ISSUE #360: Error Import Scan Results with API
Hi,

I have set up the defect dojo using the ./setup.bash (master branch) on Ubuntu 16.04.

I tried to import a scan report using the API. But it shows the following error.

`Response Body

{
  "error_message": "global name 'Resolver404' is not defined",
  "traceback": "Traceback (most recent call last):\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 221, in wrapper\n    response = callback(request, *args, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 461, in dispatch_list\n    return self.dispatch('list', request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 493, in dispatch\n    response = method(request, **kwargs)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1401, in post_list\n    updated_bundle = self.obj_create(bundle, **self.remove_api_resource_names(kwargs))\n\n  File \"/home/xxx/yyy/VulManSys/django-DefectDojo/dojo/api.py\", line 884, in obj_create\n    self.is_valid(bundle)\n\n  File \"/usr/local/lib/python2.7/dist-packages/tastypie/resources.py\", line 1313, in is_valid\n    errors = self._meta.validation.is_valid(bundle, bundle.request)\n\n  File \"/home/nadeeshani/Desktop/ExternalProducts/VulManSys/Temp/django-DefectDojo/dojo/api.py\", line 805, in is_valid\n    get_pk_from_uri(uri=bundle.data['engagement'])\n\n  File \"/home/nadeeshani/Desktop/ExternalProducts/VulManSys/Temp/django-DefectDojo/dojo/api.py\", line 748, in get_pk_from_uri\n    except Resolver404:\n\nNameError: global name 'Resolver404' is not defined\n"
}`

### PR DESCRIPTION
**Pull request by NShani**
[#360](https://github.com/OWASP/django-DefectDojo/issues/360) : Error Import Scan Results with API

### CODE REVIEW

**Comment by dkade** [comment]
Master continues with the "NameError: global name 'Resolver404' is not defined"  on ImportScanReport API. Do you know why this wasn't merged to master?

**Comment by dkade** [comment]
@NShani why did you close this before being merged to master? I'm working with the API and found all the problems you have fixed in this PR but weren't merged. You request the PR again so I don't do the same work you have done.

**Comment by dkade** [comment]
It will take some time for @devGregA check the PR but it will go, this is a huge fix and great work! :)

**Comment by devGregA** [comment]
@aaronweaver you're much more familiar with this section of code than I am do you have time to take a look this week?

**Comment by aaronweaver** [comment]
@devGregA Yes, will review.

**Comment by aaronweaver** [comment]
@NShani Thanks for the code commit. I had to make a couple changes to the model to allow null fields and adjust the timezone setting. Other than that it looks good. Would it be possible to provide me with a scrubbed Qualys WAS report and Veracode for future testing? Thx!

**Pull request closed without merging**
