### PR TITLE
Added UI Checks and 'Active' count to product type metrics

### PR DESCRIPTION
**Pull request by devGregA**

### CODE REVIEW

**Comment by devGregA** [comment]
Don't merge I need to correct something.

**Comment by devGregA** [comment]
@aaronweaver @grendel513 @cneill  this is ready for review: https://travis-ci.org/devGregA/django-DefectDojo. @mtesauro this will add prefixes. I have done thorough testing to fix the links.

**Comment by grendel513** [comment]
@devGregA pulling from master and running app yields:

`AttributeError at /login
'Settings' object has no attribute 'URL_PREFIX'
Request Method:	GET
Request URL:	http://127.0.0.1:8000/login?next=/
Django Version:	1.8.10
Exception Type:	AttributeError
Exception Value:	
'Settings' object has no attribute 'URL_PREFIX'
Exception Location:	/Users/jpaz/.virtualenvs/dojo/lib/python2.7/site-packages/django/conf/__init__.py in __getattr__, line 49
Python Executable:	/Users/jpaz/.virtualenvs/dojo/bin/python
Python Version:	2.7.12
Python Path:	
['/Users/jpaz/defect-dojo',
 '/Users/jpaz/.virtualenvs/dojo/lib/python27.zip',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-darwin',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-mac',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-tk',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-old',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-dynload',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/site-packages',
 '/Users/jpaz/defect-dojo']
Server time:	Wed, 5 Oct 2016 11:00:30 -0500`

This is because the `urls.py` is using the new prefix setting without checking that it exists.

**Comment by devGregA** [comment]
shoot. great catch. easy fix. will do this immediately.

**Comment by grendel513** [comment]
@devGregA - one more.  Product type metrics breaks when selecting period with actual findings in it:

`TypeError at /metrics/product/type
can't compare datetime.datetime to datetime.date
Request Method:	GET
Request URL:	http://127.0.0.1:8000/metrics/product/type?date=4&status=
Django Version:	1.8.10
Exception Type:	TypeError
Exception Value:	
can't compare datetime.datetime to datetime.date
Exception Location:	/Users/jpaz/defect-dojo/dojo/utils.py in get_period_counts, line 366
Python Executable:	/Users/jpaz/.virtualenvs/dojo/bin/python
Python Version:	2.7.12
Python Path:	
['/Users/jpaz/defect-dojo',
 '/Users/jpaz/.virtualenvs/dojo/lib/python27.zip',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-darwin',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-mac',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-tk',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-old',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/lib-dynload',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac',
 '/usr/local/Cellar/python/2.7.12/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages',
 '/Users/jpaz/.virtualenvs/dojo/lib/python2.7/site-packages',
 '/Users/jpaz/defect-dojo']
Server time:	Wed, 5 Oct 2016 11:18:09 -0500`

I tried and saw it break with:  past 30 days, past 90 days, current year, etc.  Any period with findings in it will break.

**Pull request merged**
