### PR TITLE
Added Import Options

### PR DESCRIPTION
**Pull request by jpbowie**
Added import functionality for:
Visual Code Grepper (An Open Source static source code analysis tool) XML and CSV output
OWASP Dependency Check XML output
Generic Findings CSV file

### CODE REVIEW

**Comment by devGregA** [comment]
man, @jpbowie, great work! I've reviewed and everything looks good to me, but I'll wait for @grendel513 and @aaronweaver to weigh in.

**Comment by aaronweaver** [comment]
@devGregA, @jpbowie Looks good! +1 on the unit tests as well. Would you also happen to have the sample files as well? If so could you add them here? https://github.com/OWASP/django-DefectDojo/tree/master/docker/sample_data/scans

**Comment by grendel513** [comment]
@devGregA, @jpbowie - taking a look now.

**Comment by grendel513** [comment]
@devGregA, @aaronweaver, @jpbowie - Thanks for all this work @jpbowie, the more tools that are integrated the greater the value Dojo provides.  Here are my notes/thoughts:

1.  I don's see where these templates are used: `add_dependency_check_scan.html`, `add_generic_import.html`, `add_vcg_scan.html` - looks like they can be omitted from the pull request.
2.  The file `dojo/help/add_generic_import_instructions.html` referenced in the template `dojo/templates/dojo/import_scan_results.html` does not seem to exist.  Additionally, I would recommend this be added to the readthedocs rst file (https://github.com/OWASP/django-DefectDojo/blob/master/docs/features.rst#imports) where all imports are already slightly documented.  A new page can be added for the CVS format, etc...but it should be part of readthedocs, and then linked to from the template to keep all documentation in a central location.  The `help` directory does not exists now and I don't feel there is a need for it since we leverage readthedocs.  The readthedocs documentation will auto generate when the changes are committed and merged into the branches.

If you can address these we can merge the pull request right away.

Great job on including tests!

**Comment by jpbowie** [comment]
Thanks, I'll make these changes and clean up a few other things with the generic file import that have been bothering me.

**Comment by jpbowie** [comment]
I think I've made all of the changes and committed them.  Let me know if there's anything I missed.  Thanks.

**Comment by devGregA** [comment]
Hi @jpbowie great work! I've been pushing to try to get the word out about Dojo in the hopes that we could get more awesome contributors like yourself. If you don't mind me asking how did you find out about Dojo?

**Comment by jpbowie** [comment]
I was at AppSecUSA 2016 and attended the "Creating and Automating your own AppSec Pipeline" course by Matt Tesauro where we used DefectDojo in some of our labs.  I had been evaluating another product, but after the class I thought I'd try DefectDojo, make a few customizations,  and hopefully contribute back to the community.

**Pull request merged**
